export const countries = [
  {
    id: 1,
    name: "India",
    population: 1393409038,
    states: [
      "Karnataka",
      "Uttar Pradesh",
      "Maharashtra",
      "Bihar",
      "West Bengal",
      "Madhya Pradesh",
      "Tamil Nadu",
      "Rajasthan",
    ],
  },
  {
    id: 2,
    name: "United States",
    population: 331002651,
    states: [
      "California",
      "Texas",
      "Florida",
      "New York",
      "Illinois",
      "Pennsylvania",
      "Ohio",
    ],
  },

  {
    id: 3,
    name: "China",
    population: 1444216107,
    states: [
      "Guangdong",
      "Shandong",
      "Henan",
      "Sichuan",
      "Jiangsu",
      "Hebei",
      "Hunan",
    ],
  },
  {
    id: 4,
    name: "Brazil",
    population: 212559417,
    states: [
      "São Paulo",
      "Minas Gerais",
      "Rio de Janeiro",
      "Bahia",
      "Paraná",
      "Rio Grande do Sul",
      "Pernambuco",
    ],
  },
  {
    id: 5,
    name: "Russia",
    population: 146171015,
    states: [
      "Moscow",
      "Saint Petersburg",
      "Novosibirsk",
      "Yekaterinburg",
      "Nizhny Novgorod",
      "Kazan",
      "Chelyabinsk",
    ],
  },
  {
    id: 6,
    name: "Australia",
    population: 25687041,
    states: [
      "New South Wales",
      "Victoria",
      "Queensland",
      "Western Australia",
      "South Australia",
      "Tasmania",
      "ACT",
    ],
  },
  {
    id: 7,
    name: "Canada",
    population: 37742154,
    states: [
      "Ontario",
      "Quebec",
      "British Columbia",
      "Alberta",
      "Manitoba",
      "Saskatchewan",
      "Nova Scotia",
    ],
  },
  {
    id: 8,
    name: "Germany",
    population: 83783942,
    states: [
      "North Rhine-Westphalia",
      "Bavaria",
      "Baden-Württemberg",
      "Lower Saxony",
      "Hesse",
      "Saxony",
      "Berlin",
    ],
  },
  {
    id: 9,
    name: "South Africa",
    population: 59308690,
    states: [
      "Gauteng",
      "KwaZulu-Natal",
      "Western Cape",
      "Eastern Cape",
      "Limpopo",
      "Mpumalanga",
      "Free State",
    ],
  },
  {
    id: 10,
    name: "Japan",
    population: 126476461,
    states: [
      "Tokyo",
      "Osaka",
      "Kanagawa",
      "Aichi",
      "Hokkaido",
      "Hyogo",
      "Fukuoka",
    ],
  },
];