export const stateForCountries = [
  {
    Country_Name: "India",
    states: [
      { name: "Karnataka", capital: "Bengaluru", population: 61095297, hdi: 0.74 },
      { name: "Andhra Pradesh", capital: "Amaravati", population: 49577103, hdi: 0.70 },
      { name: "Arunachal Pradesh", capital: "Itanagar", population: 1383727, hdi: 0.64 },
      { name: "Assam", capital: "Dispur", population: 35607039, hdi: 0.68 },
      { name: "Bihar", capital: "", population: null, hdi: null },
      { name: "Chhattisgarh", capital: "", population: null, hdi: null },
      { name: "Goa", capital: "", population: null, hdi: null },
      { name: "Gujarat", capital: "", population: null, hdi: null },
      { name: "Haryana", capital: "", population: null, hdi: null },
      { name: "Himachal Pradesh", capital: "", population: null, hdi: null },
      { name: "Jharkhand", capital: "", population: null, hdi: null },
      { name: "Kerala", capital: "", population: null, hdi: null },
      { name: "Madhya Pradesh", capital: "", population: null, hdi: null },
      { name: "Maharashtra", capital: "", population: null, hdi: null },
      { name: "Manipur", capital: "", population: null, hdi: null },
      { name: "Meghalaya", capital: "", population: null, hdi: null },
      { name: "Mizoram", capital: "", population: null, hdi: null },
      { name: "Nagaland", capital: "", population: null, hdi: null },
      { name: "Odisha", capital: "", population: null, hdi: null },
      { name: "Punjab", capital: "", population: null, hdi: null },
      { name: "Rajasthan", capital: "", population: null, hdi: null },
      { name: "Sikkim", capital: "", population: null, hdi: null },
      { name: "Tamil Nadu", capital: "", population: null, hdi: null },
      { name: "Telangana", capital: "", population: null, hdi: null },
      { name: "Tripura", capital: "", population: null, hdi: null },
      { name: "Uttar Pradesh", capital: "", population: null, hdi: null },
      { name: "Uttarakhand", capital: "", population: null, hdi: null },
      { name: "West Bengal", capital: "", population: null, hdi: null },
    ],
  },
  {
    Country_Name: "USA",
    states: [
      { name: "California", capital: "Sacramento", population: 39538223, hdi: 0.92 },
      { name: "Texas", capital: "Austin", population: 29145505, hdi: 0.89 },
      { name: "Florida", capital: "Tallahassee", population: 21538187, hdi: 0.91 },
      { name: "New York", capital: "Albany", population: 20201249, hdi: 0.92 },
      { name: "Pennsylvania", capital: "", population: null, hdi: null },
      { name: "Illinois", capital: "", population: null, hdi: null },
      { name: "Ohio", capital: "", population: null, hdi: null },
      { name: "Georgia", capital: "", population: null, hdi: null },
      { name: "North Carolina", capital: "", population: null, hdi: null },
      { name: "Michigan", capital: "", population: null, hdi: null },
    ],
  },
  {
    Country_Name: "Germany",
    states: [
      { name: "Baden-Württemberg", capital: "Stuttgart", population: 11069533, hdi: 0.95 },
      { name: "Bavaria", capital: "Munich", population: 13124737, hdi: 0.94 },
      { name: "Berlin", capital: "Berlin", population: 3669491, hdi: 0.96 },
      { name: "Hamburg", capital: "Hamburg", population: 1845229, hdi: 0.94 },
      { name: "Hesse", capital: "", population: null, hdi: null },
      { name: "Lower Saxony", capital: "", population: null, hdi: null },
      { name: "Mecklenburg-Vorpommern", capital: "", population: null, hdi: null },
      { name: "North Rhine-Westphalia", capital: "", population: null, hdi: null },
      { name: "Rhineland-Palatinate", capital: "", population: null, hdi: null },
      { name: "Saarland", capital: "", population: null, hdi: null },
    ],
  },
  {
    Country_Name: "France",
    states: [
      { name: "Île-de-France", capital: "Paris", population: 12381000, hdi: 0.94 },
      { name: "Provence-Alpes-Côte d'Azur", capital: "Marseille", population: 5052000, hdi: 0.92 },
      { name: "Occitanie", capital: "Toulouse", population: 6000000, hdi: 0.90 },
      { name: "Nouvelle-Aquitaine", capital: "Bordeaux", population: 5900000, hdi: 0.91 },
      { name: "Hauts-de-France", capital: "", population: null, hdi: null },
      { name: "Grand Est", capital: "", population: null, hdi: null },
      { name: "Brittany", capital: "", population: null, hdi: null },
      { name: "Normandy", capital: "", population: null, hdi: null },
    ],
  },
  {
    Country_Name: "Russia",
    states: [
      { name: "Moscow", capital: "Moscow", population: 12615279, hdi: 0.89 },
      { name: "Saint Petersburg", capital: "Saint Petersburg", population: 5383890, hdi: 0.91 },
      { name: "Novosibirsk Oblast", capital: "Novosibirsk", population: 2804415, hdi: 0.85 },
      { name: "Sverdlovsk Oblast", capital: "Yekaterinburg", population: 4322463, hdi: 0.87 },
      { name: "Krasnodar Krai", capital: "", population: null, hdi: null },
      { name: "Primorsky Krai", capital: "", population: null, hdi: null },
      { name: "Tatarstan", capital: "", population: null, hdi: null },
      { name: "Bashkortostan", capital: "", population: null, hdi: null },
    ],
  },
];
